all:
	$(MAKE) -C "/home/valentin/Documents/PFEE/EXCELKissat/PFEE/timeExtraction/all_kissat/Kissat_MAB-HyWalk/build"
kissat:
	$(MAKE) -C "/home/valentin/Documents/PFEE/EXCELKissat/PFEE/timeExtraction/all_kissat/Kissat_MAB-HyWalk/build" kissat
tissat:
	$(MAKE) -C "/home/valentin/Documents/PFEE/EXCELKissat/PFEE/timeExtraction/all_kissat/Kissat_MAB-HyWalk/build" tissat
clean:
	rm -f "/home/valentin/Documents/PFEE/EXCELKissat/PFEE/timeExtraction/all_kissat/Kissat_MAB-HyWalk"/makefile
	-$(MAKE) -C "/home/valentin/Documents/PFEE/EXCELKissat/PFEE/timeExtraction/all_kissat/Kissat_MAB-HyWalk/build" clean
	rm -rf "/home/valentin/Documents/PFEE/EXCELKissat/PFEE/timeExtraction/all_kissat/Kissat_MAB-HyWalk/build"
coverage:
	$(MAKE) -C "/home/valentin/Documents/PFEE/EXCELKissat/PFEE/timeExtraction/all_kissat/Kissat_MAB-HyWalk/build" coverage
indent:
	$(MAKE) -C "/home/valentin/Documents/PFEE/EXCELKissat/PFEE/timeExtraction/all_kissat/Kissat_MAB-HyWalk/build" indent
test:
	$(MAKE) -C "/home/valentin/Documents/PFEE/EXCELKissat/PFEE/timeExtraction/all_kissat/Kissat_MAB-HyWalk/build" test
.PHONY: all clean coverage indent kissat test tissat
