all:
	$(MAKE) -C "/home/valentin/Documents/PFEE/EXCELKissat/PFEE/timeExtraction/all_kissat/ekissat-mab-db-v1/build"
kissat:
	$(MAKE) -C "/home/valentin/Documents/PFEE/EXCELKissat/PFEE/timeExtraction/all_kissat/ekissat-mab-db-v1/build" kissat
tissat:
	$(MAKE) -C "/home/valentin/Documents/PFEE/EXCELKissat/PFEE/timeExtraction/all_kissat/ekissat-mab-db-v1/build" tissat
clean:
	rm -f "/home/valentin/Documents/PFEE/EXCELKissat/PFEE/timeExtraction/all_kissat/ekissat-mab-db-v1"/makefile
	-$(MAKE) -C "/home/valentin/Documents/PFEE/EXCELKissat/PFEE/timeExtraction/all_kissat/ekissat-mab-db-v1/build" clean
	rm -rf "/home/valentin/Documents/PFEE/EXCELKissat/PFEE/timeExtraction/all_kissat/ekissat-mab-db-v1/build"
coverage:
	$(MAKE) -C "/home/valentin/Documents/PFEE/EXCELKissat/PFEE/timeExtraction/all_kissat/ekissat-mab-db-v1/build" coverage
indent:
	$(MAKE) -C "/home/valentin/Documents/PFEE/EXCELKissat/PFEE/timeExtraction/all_kissat/ekissat-mab-db-v1/build" indent
test:
	$(MAKE) -C "/home/valentin/Documents/PFEE/EXCELKissat/PFEE/timeExtraction/all_kissat/ekissat-mab-db-v1/build" test
.PHONY: all clean coverage indent kissat test tissat
